### PR TITLE
delete obsolete Apache 1.3 code and macros

### PR DESCRIPTION
**Pull request by mgkuhn**
Just to make source code easier to read and review.

### CODE REVIEW

**Comment by jw35** [comment]
Changes merged.

**Comment by jw35** [comment]
...and I worked out how to manage the version number and CHANGES file update myself!

**Comment by mgkuhn** [comment]
I would bump the version number only for actual new releases, which should be
- tagged with "git tag"
- announced on cs-raven-announce@lists
- provided as various packages on http://raven.cam.ac.uk/project/apache/
That sort of thing seems only worth doing after significant functional improvements, not after minor cosmetic changes like this one. For unreleased versions, the "git describe" command automatically gives a handy unique identifier (essentially the last version tag and the number of commits since).

**Comment by jw35** [comment]
I admit I don't understand how best to manage the whole update/release cycle here. The problem with NOT bumping the version number is that it gets burnt into the resulting binary and it announces its version number in various places. Without a bump, we'll end up with multiple different copies of the module all calling themselves the same version as the last release. That way madness lies.

Ideally we need a neat trick to use the 'git describe' output as the version number for unreleased versions.

**Comment by mgkuhn** [comment]
There are various neat tricks to include "git describe" output automatically into the binary, but they usually depend on Unix shell and make. I've not yet done this on a project that is also meant to compile on Win32.

**Comment by mgkuhn** [comment]
Could you please run something like
```
git tag v2.0.2 0ec6d419b1033ee302c114e464cea243f8bc0b95
git push <your-github-remote> v2.0.2
```
to add a tag to the commit that best seems to correspond to what was released in http://raven.cam.ac.uk/project/apache/files/mod_ucam_webauth-2.0.2.tar.gz?

Having at least one tag makes it then easier to play around with `git describe`, etc.

Optionally, you can also gpg sign your commit (`git tag -s`).

Alternatively, you can also [create a release on github](https://help.github.com/articles/about-releases/), which is essentially the same as adding a tag (plus optionally adding some github metadata, such as release notes).

**Comment by jw35** [comment]
Tag created

**Pull request merged**
